### ISSUE TITLE
An error occurred while trying communicate with the server

### ISSUE THREAD

**Issue by somedolphin** [ilesinge/scuttloid#1]
Hey there, this app looks great but I keep getting this error no matter what I do.
My server address is 
http://isaacthompson.com/bmarks/www/
Thanks again!

**Comment by somedolphin** [comment]
Ok I found the problem :) Somehow I had made all the php files executable. It's all good now. Thanks for your time and for the app! Blessings, ike

**Comment by ilesinge** [comment]
Hey, sorry I didn't answer your question ! I just noticed I don't receive github notifications... (changed now)
I'm glad Scuttloid may be useful to you. If you have any improvement idea, please share it :)
