### ISSUE TITLE
Cannot connect to server

### ISSUE THREAD

**Issue by snte** [ilesinge/scuttloid#19]
Hi, thanks for creating an Android client for Semantic Scuttle :)

I have installed SemanticScuttle-0.98.5, and try to connect to it, but i receive errors no matter what i try. What is the correct syntax for the server entry? E.g. if can access my scuttle under http://example.org/scuttle (or https://...)? I tried every combination, with http and without, trailing slash and without, ...

My account pass has no special characters in it by the way (i had trouble logging in with 'scuttle' from play store with a pass with special characters).

Thanks in advance!!

**Comment by snte** [comment]
... by the way: i get "server address seems to be wrong" most of my attempts, but if i just use example.org (without "/scuttle") i get "user pass wrong" (but there is nothing installed in root)

Any help is appreciated!

EDIT: Just tried version 1.0.1, and it works right away :)

**Comment by ilesinge** [comment]
Hi ! Thanks for the report.
If version 1.0.1 works but not 1.1, it would surely mean that URL rewriting is not enabled on your server.

To test that:
1. Access http://www.example.org/scuttle/api/posts_all.php in your desktop web browser. It should ask you for a password.
2. Access http://www.example.org/scuttle/api/posts/all in your desktop web browser. It should ask you for a password in the same way. If it doesn't, you should enable (or ask your server's admin to enable) Apache mod_rewrite.

On Debian-based servers it is usually done with the following command:
sudo a2enmod rewrite

**Comment by snte** [comment]
Thanks for the hint!

I disabled the RewriteRules section in .htaccess in the SemanticScuttle installation because it returned internal server errors (500) on my host (Uberspace).

This is because of 'Options +FollowSymlinks' (for Uberspace users more here: http://blog.jonaspasche.com/2014/07/11/followsymlinks-vs-symlinksifownermatch). So i just removed 'Options +FollowSymlinks', and this works for now, also in Scuttloid v1.1. :)

Thanks!!

**Comment by ilesinge** [comment]
Cool that it worked :)
