### ISSUE TITLE
My server URL is said to be incorrect

### ISSUE THREAD

**Issue by nytche** [ilesinge/scuttloid#20]
Hello,

I try to connected Scuttloir (downloaded from F-Droid) with my server, at this URL: http://pin.nitche.org
But i have always a message saying that my server address is incorrect.
Is this an issue or am I doing something wrong?

**Comment by pascalfree** [comment]
You'll probably have to enable mod_rewrite on your server. See #19
I think in a future release scuttloid should have a fallback if mod_rewrite can not be enabled.

**Comment by nytche** [comment]
just checked, mod_rewrite is already enabled. :/

**Comment by pascalfree** [comment]
What is the content of your /www/.htaccess file?
There should be a block like this one:

```
# Rewrite clean URLs onto real files
<IfModule mod_rewrite.c>
Options +FollowSymlinks
RewriteEngine On
RewriteCond %{REQUEST_FILENAME}.php -f
RewriteRule ^([^/.]+)/?(.*)$ /$1.php/$2 [QSA,L]
RewriteRule ^api/([a-z]+)/([a-z]+) /api/$1_$2.php
</IfModule>
```

Then it should work.
PS: alternatively you can try to use scuttloid v1.0.1 (also available in fdroid) in the meantime.

**Comment by nytche** [comment]
working with 1.0.1, thank you!
